-- ~/.config/nvim/lua/config/settings.lua

-- Load plugins
require('plugins')

-- Load plugin configurations
require('config.lsp')
require('config.telescope')
require('config.chatgpt')
require('config.themes')
require('config.whichkey')
require('config.trouble')
require('config.noice')
require('config.notify')
require('config.nvim_tree')
require('config.lualine')
require('config.bufferline')
require('config.toggleterm')
require('config.indentline')
require('config.colorizer')
require('config.copilot_chat')
require('config.diffview')
require('config.gitsigns')
require('config.aerial')
require('config.navic')
require('config.codewindow')
--require('config.dap')
--require('config.todo_comments')
require('config.copilot')
--require('config.cyberdream')
-- require('config.sqls')
-- require('config.dadbod')
-- Owns Plugins
require('config.envolver')
require('config.ticket_notes')
require('config.ticket_playground')
require('config.pomodoro')
-- Load keymaps
require('keymaps')
require('cocconfig')
-- require('abbrev')
